/**
 ****
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ****
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ****
 */

#include <stdint.h>
#include "DMA.h"
#include "RCC.h"
#include"NVIC.h"
#include "rtc.h"
#include "GPIO.h"
#include "EXTI.h"
#include "UART.h"
#include "SPI.h"
uint32_t seconds_;
DMA_Handle_t HDMA_Stream6;
DMA_Handle_t HDMA_Stream5;
i2c_handle_t i2c_hdmi;
UART_Handle_t USART_Handle;
SPI_Handle_t SPI_Handle;
EXTI_Handle_t EXTI_1;
int main(void){
	RCC_AHBEnableClock(0);
	RCC_AHBEnableClock(1);
	RCC_APB1_EnableClock(17);
	RCC_APB1_EnableClock(22);
	RCC_APB1_EnableClock(21);
	RCC_APB2_enableClock(12);

	NVIC_Pref_en(SPI1_IRQ);
	NVIC_Pref_en(DMA1_Stream6);
	NVIC_Pref_en(DMA1_Stream5);
	NVIC_Pref_en(31);
	NVIC_Pref_en(32);
	NVIC_Pref_en(38);
	NVIC_Pref_en(7);


	Pin_Config_t esp_int_pin=
		{

		.Port=PortA,
		.Pin=Pin12,
		.mode=output,
		.output_mode=push_pull,
		.pullmode=pull_up
		};

	Pin_Config_t tx_pin=
	{

	.Port=PortA,
	.Pin=Pin2,
	.mode=altfun,
	.output_mode=push_pull,
	.AltFun=AF7
	};
		Pin_Config_t rx_pin=
	{

	.Port=PortA,
	.Pin=Pin3,
	.mode=altfun,
	.output_mode=push_pull,
	.AltFun=AF7
	};
		USART_Handle.USART_Type=USART_2;
		USART_Handle.TC_Interrupt=Transmit_Dis;
		USART_Handle.TXE_Interrupt=TXE_Interrupt_Dis;
		USART_Handle.BaudRate=115200;
		USART_Handle.CTSE=CTS_Dis;
		USART_Handle.Stop_Bit_Mode=one;
		USART_Handle.Transmit_Status=Transmit_En;
		USART_Handle.OS=Eight_Data_Bits;
		USART_Handle.Clock_Status=Clock_Dis;
		USART_Handle.Duplex_Mode=Full_Duplex;
		USART_Handle.CTSE=0;
		USART_Handle.Recieve_Status=Recieve_En;
		USART_Handle.PE_int_en=0;
		USART_Handle.RXNEIE_Interrupt=0;
		USART_Handle.RTSE=0;
	Pin_Config_t SDA={
				.Port=PortB,
				.Pin=7,
				.mode=altfun,
				.AltFun=4,
				.output_mode=open_drain,
				.pullmode=pull_up,
				.speed=fast_speed
		};

	Pin_Config_t SCL={
			.Port=PortB,
			.Pin=6,
			.mode=altfun,
			.AltFun=4,
			.output_mode=open_drain,
			.pullmode=pull_up,
			.speed=fast_speed

	};

	 	 	i2c_hdmi.i2c_number=1;
			i2c_hdmi.mode=SM;
			i2c_hdmi.DMA_int=0;
			i2c_hdmi.sys_int=I2C_Sys_Dis;
			i2c_hdmi.Add_Mode=ten_bit;
			i2c_hdmi.clock = 16;


	Pin_Config_t int_pin={
									.Port=PortA,
									.Pin=1,
									.mode=input,
									.pullmode=pull_up
								};


		EXTI_1.EXTI_num=EXTI1;
		EXTI_1.INT_status=EXTI_Int_En;
		EXTI_1.Rising_Edge=Rising_Edge_Dis;
		EXTI_1.Falling_Edge=Falling_Edge_En;

	Pin_Config_t mosi_pin={
			.Port=PortB,
			.Pin=Pin5,
			.mode=altfun,
			.AltFun=AF5


	};
	Pin_Config_t miso_pin={
				.Port=PortB,
				.Pin=Pin4,
				.mode=altfun,
				.AltFun=AF5


		};

	Pin_Config_t sck_pin={
					.Port=PortB,
					.Pin=Pin3,
					.mode=altfun,
					.AltFun=AF5


			};

			SPI_Handle.SPI_Number=SPI1;
			SPI_Handle.SPI_En=En;
			SPI_Handle.Duplex=Full_Duplex_SPI;
			SPI_Handle.Master_Slave=Master;
			SPI_Handle.RXNEIE=En;
			SPI_Handle.TXEIE=Dis;
			SPI_Handle.SW_Slave_Managament=En;
			SPI_Handle.SSI=En;



	DMA_Sys_Init(DMA1_Stream6,0);
	DMA_Sys_Init(DMA1_Stream5,0);
	DMA1_Handle_Init(&HDMA_Stream6,Stream6,Channel1,M2P);
	DMA1_Handle_Init(&HDMA_Stream5,Stream5,Channel1,P2M);


	DMA_Stream_Init(&HDMA_Stream6);
	DMA_Stream_Init(&HDMA_Stream5);

	GPIO_INIT(&int_pin);
	GPIO_INIT(&SDA);
	GPIO_INIT(&SCL);
	GPIO_INIT(&tx_pin);
	GPIO_INIT(&rx_pin);
	GPIO_INIT(&mosi_pin);
	GPIO_INIT(&miso_pin);
	GPIO_INIT(&sck_pin);
	GPIO_INIT(&esp_int_pin);


	USART_init(&USART_Handle);
	EXTI_Init(&EXTI_1);
	i2c_init(&i2c_hdmi);
	EXTI_Init(&EXTI_1);
	EXTI_Stop(&EXTI_1);
	EXTI_Init(&EXTI_1);
	SPI_Init(&SPI_Handle);
	uint8_t speed_val=30;
	uint8_t recived_data[7]={1,1,1,1,1,1,1};

	SPI_Send_Data_IT(&SPI_Handle,&speed_val);

	RTC_Control_Init(&i2c_hdmi);
	uint8_t time_tobe_sent[7];

	time_tobe_sent[0]=50;
	time_tobe_sent[1]=1;
	time_tobe_sent[2]=1;
	time_tobe_sent[3]=1;
	time_tobe_sent[4]=1;
	time_tobe_sent[5]=1;
	time_tobe_sent[6]=1;
	send_time_to_rtc_DMA(&i2c_hdmi,&time_tobe_sent);
	uint8_t alarm_data[5];

	alarm_data[0]=0;
	alarm_data[1]=2;
	alarm_data[2]=1;
	alarm_data[3]=1;
	alarm_data[4]=1;


	Set_RTC_Alarm_DMA(&i2c_hdmi,&alarm_data);

		recieve_ControlReg_from_rtc_DMA(&i2c_hdmi,&recived_data,14);
	Start_Menu();

		uint8_t sec_Reg=0;
















while(1){


	recieve_time_from_rtc_DMA(&i2c_hdmi,&recived_data);
	recieve_alarm1_time_from_rtc_DMA(&i2c_hdmi,&recived_data);

	recieve_ControlReg_from_rtc_DMA(&i2c_hdmi,&recived_data,14);
	recieve_ControlReg_from_rtc_DMA(&i2c_hdmi,&recived_data,15);



}


	for(;;);
}




void EXTI1_IRQHandler(void){
	char Alarm_Triggered[]="\nAlarm Triggered\n\r";
	uint8_t turn_on_light_flag=101;
	uint8_t recived_data=90;
//	recieve_ControlReg_from_rtc_DMA(&i2c_hdmi,&recived_data,14);
	USART_Send_Poll(&USART_Handle,19,&Alarm_Triggered);
	SPI_Send_Data_IT(&SPI_Handle,&turn_on_light_flag);

	RTC_Reset_Status(&i2c_hdmi);
	pin_set_reset(PORTA,12,on);
	pin_set_reset(PORTA,12,off);

	EXTI->PR|=(0b1<<1);

}
